<!DOCTYPE html>
<html>
	<head>
		<title><?= $this->getConfig('application/basename') ?> - An error occured</title>

		<!-- Css include -->
		<link href="<?= $this->baseUrlHelper('etc/asset/fewlines/styles/css/application.css') ?>" rel="stylesheet" type="text/css" />
	</head>
	<body class="exception-page">
		<div id="page">
			<?php if($this->getEnvironment()->isLocal()): ?>
			<?= $this->renderView() ?>
			<?php else: ?>
			<div class="non-local-error">Something went wrong!</div>
			<?php endif; ?>
		</div>
	</body>
</html>