// This file was autogenerated by ../../../lib/js/third-party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../fewlines/Fewlines/Application.js', ['Fewlines', 'Fewlines.Application'], [], false);
